"""Format-version-1 rendering, golden bytes, and structural self-validation."""

from dataclasses import replace
from pathlib import Path

import pytest
from conftest import (
    CORE_TEXT,
    GOLDEN,
    MANIFEST_FIXTURES,
    PYTHON_TEXT,
    Bundle,
    make_bundle,
)

from agents_md_compiler import rendering
from agents_md_compiler.errors import RenderError, RenderProblem
from agents_md_compiler.hashing import sha256_bytes
from agents_md_compiler.lockfile import build_lock, lock_digest, serialize_lock
from agents_md_compiler.manifest import load_manifest
from agents_md_compiler.models import (
    BUNDLE_TITLE,
    RENDER_FORMAT_VERSION,
    BundleLock,
    CompiledBundle,
    LockedModule,
    RenderedBundle,
    SourceSnapshot,
)
from agents_md_compiler.sources import read_sources
from agents_md_compiler.state import compile_bundle

ABSENT_TARGET = Path("/nonexistent/agents-md-compiler-test-target/AGENTS.md")


def compiled_for(manifest_path: Path) -> CompiledBundle:
    """Compile a bundle from a manifest on disk.

    Args:
        manifest_path: Manifest to read.

    Returns:
        The compiled bundle.
    """
    return compile_bundle(load_manifest(manifest_path), target=ABSENT_TARGET)


def rendered_for(manifest_path: Path) -> RenderedBundle:
    """Render a bundle from a manifest on disk.

    Args:
        manifest_path: Manifest to read.

    Returns:
        The rendered bundle.
    """
    manifest = load_manifest(manifest_path)
    snapshots = read_sources(manifest.modules)
    lock = build_lock(manifest, snapshots)
    return rendering.render_bundle(
        bundle_id=manifest.bundle_id,
        manifest_sha256=manifest.sha256,
        lock_sha256=lock_digest(lock),
        snapshots=snapshots,
    )


def test_rendered_bytes_match_the_hand_authored_golden() -> None:
    manifest = load_manifest(MANIFEST_FIXTURES / "minimal.toml")
    snapshots = read_sources(manifest.modules)
    lock = build_lock(manifest, snapshots)
    digest = sha256_bytes(serialize_lock(lock))
    rendered = rendering.render_bundle(
        bundle_id=manifest.bundle_id,
        manifest_sha256=manifest.sha256,
        lock_sha256=digest,
        snapshots=snapshots,
    )
    expected = (
        (GOLDEN / "minimal.render.md.tmpl")
        .read_text(encoding="utf-8")
        .replace("__LOCK_SHA256__", digest)
        .encode("utf-8")
    )
    assert rendered.data == expected


def test_the_header_has_exactly_seven_lines(bundle: Bundle) -> None:
    rendered = rendered_for(bundle.manifest)
    lines = rendered.data.split(b"\n")
    assert lines[0] == BUNDLE_TITLE.encode("ascii")
    assert lines[1] == b""
    assert (
        lines[2]
        == f"<!-- agents-md-compiler:generated format={RENDER_FORMAT_VERSION} -->".encode()
    )
    assert lines[3].startswith(b"<!-- bundle-id: ")
    assert lines[4].startswith(b"<!-- manifest-sha256: ")
    assert lines[5].startswith(b"<!-- lock-sha256: ")
    assert lines[6].startswith(b"<!-- Do not edit this file.")
    assert lines[7] == b""


def test_output_starts_with_a_heading_and_ends_with_one_lf(bundle: Bundle) -> None:
    data = rendered_for(bundle.manifest).data
    assert data.startswith(b"#")
    assert data.endswith(b"-->\n")
    assert not data.endswith(b"\n\n")


def test_exact_source_bytes_are_preserved(bundle: Bundle) -> None:
    data = rendered_for(bundle.manifest).data
    for source in bundle.modules.values():
        assert source.read_bytes() in data


def test_each_module_is_wrapped_by_its_own_markers(three_module_bundle: Bundle) -> None:
    rendered = rendered_for(three_module_bundle.manifest)
    text = rendered.data.decode("utf-8")
    for module in rendered.modules:
        assert rendering.begin_marker(module) in text
        assert rendering.end_marker(module) in text


def test_first_middle_and_last_modules_are_all_present_in_order(
    three_module_bundle: Bundle,
) -> None:
    rendered = rendered_for(three_module_bundle.manifest)
    text = rendered.data.decode("utf-8")
    positions = [
        text.index(f"module-begin id={module.id} ") for module in rendered.modules
    ]
    assert [module.id for module in rendered.modules] == ["core", "python", "extras"]
    assert positions == sorted(positions)
    assert "# Core Policy" in text
    assert "# Python Policy" in text
    assert "# Extra Policy" in text


def test_one_empty_line_precedes_every_begin_marker(
    three_module_bundle: Bundle,
) -> None:
    data = rendered_for(three_module_bundle.manifest).data
    for chunk in data.split(rendering.MODULE_BEGIN_COUNT_TOKEN)[:-1]:
        assert chunk.endswith(b"\n\n")


def test_no_empty_line_separates_content_from_its_end_marker(bundle: Bundle) -> None:
    rendered = rendered_for(bundle.manifest)
    for module in rendered.modules:
        marker = (rendering.end_marker(module) + "\n").encode("ascii")
        index = rendered.data.index(marker)
        assert rendered.data[index - 2 : index] != b"\n\n"


def test_rendering_is_deterministic(bundle: Bundle) -> None:
    assert rendered_for(bundle.manifest).data == rendered_for(bundle.manifest).data


def test_output_contains_no_volatile_value(bundle: Bundle) -> None:
    text = rendered_for(bundle.manifest).data.decode("utf-8")
    for forbidden in (
        str(bundle.root),
        str(bundle.manifest),
        "0.1.0",
        "20260",
        "/tmp",
        "/private/var",
    ):
        assert forbidden not in text


def test_output_contains_no_absolute_source_path(bundle: Bundle) -> None:
    text = rendered_for(bundle.manifest).data.decode("utf-8")
    for source in bundle.modules.values():
        assert str(source) not in text


def test_reordering_the_manifest_reorders_the_output(tmp_path: Path) -> None:
    forward = make_bundle(
        tmp_path / "a", module_texts=(("core", CORE_TEXT), ("python", PYTHON_TEXT))
    )
    reverse = make_bundle(
        tmp_path / "b", module_texts=(("python", PYTHON_TEXT), ("core", CORE_TEXT))
    )
    assert [m.id for m in rendered_for(forward.manifest).modules] == ["core", "python"]
    assert [m.id for m in rendered_for(reverse.manifest).modules] == ["python", "core"]


def test_an_invalid_bundle_identifier_is_refused() -> None:
    with pytest.raises(RenderError) as raised:
        rendering.render_bundle(
            bundle_id="Bad_Id",
            manifest_sha256="a" * 64,
            lock_sha256="b" * 64,
            snapshots=(),
        )
    assert raised.value.problem is RenderProblem.BAD_IDENTIFIER


@pytest.mark.parametrize(
    ("manifest_digest", "lock_sha"),
    [("short", "b" * 64), ("a" * 64, "short")],
    ids=["manifest-digest", "lock-digest"],
)
def test_an_invalid_header_digest_is_refused(
    manifest_digest: str, lock_sha: str
) -> None:
    with pytest.raises(RenderError) as raised:
        rendering.render_bundle(
            bundle_id="valid",
            manifest_sha256=manifest_digest,
            lock_sha256=lock_sha,
            snapshots=(),
        )
    assert raised.value.problem is RenderProblem.BAD_DIGEST


def snapshot(
    *,
    module_id: str = "core",
    data: bytes = b"# Core\n",
    digest: str | None = None,
    size: int | None = None,
) -> SourceSnapshot:
    """Build a snapshot, optionally with a deliberately wrong digest or size.

    Args:
        module_id: Module identifier.
        data: Content bytes.
        digest: Override digest.
        size: Override declared size.

    Returns:
        The snapshot.
    """
    return SourceSnapshot(
        id=module_id,
        lexical_source="core.md",
        resolved_source=Path("/example/core.md"),
        data=data,
        sha256=sha256_bytes(data) if digest is None else digest,
        size_bytes=len(data) if size is None else size,
    )


def test_an_invalid_module_identifier_is_refused() -> None:
    with pytest.raises(RenderError) as raised:
        rendering.render_bundle(
            bundle_id="valid",
            manifest_sha256="a" * 64,
            lock_sha256="b" * 64,
            snapshots=(snapshot(module_id="Core"),),
        )
    assert raised.value.problem is RenderProblem.BAD_IDENTIFIER


def test_an_invalid_module_digest_is_refused() -> None:
    with pytest.raises(RenderError) as raised:
        rendering.render_bundle(
            bundle_id="valid",
            manifest_sha256="a" * 64,
            lock_sha256="b" * 64,
            snapshots=(snapshot(digest="nope"),),
        )
    assert raised.value.problem is RenderProblem.BAD_DIGEST


def test_a_declared_size_that_disagrees_with_the_content_is_refused() -> None:
    with pytest.raises(RenderError) as raised:
        rendering.render_bundle(
            bundle_id="valid",
            manifest_sha256="a" * 64,
            lock_sha256="b" * 64,
            snapshots=(snapshot(size=99),),
        )
    assert raised.value.problem is RenderProblem.BAD_SIZE


def test_self_validation_accepts_freshly_rendered_bytes(
    three_module_bundle: Bundle,
) -> None:
    manifest = load_manifest(three_module_bundle.manifest)
    snapshots = read_sources(manifest.modules)
    lock = build_lock(manifest, snapshots)
    digest = lock_digest(lock)
    rendered = rendering.render_bundle(
        bundle_id=manifest.bundle_id,
        manifest_sha256=manifest.sha256,
        lock_sha256=digest,
        snapshots=snapshots,
    )
    rendering.validate_rendered(rendered.data, lock, digest)


def validated_parts(manifest_path: Path) -> tuple[bytes, BundleLock, str]:
    """Produce rendered bytes plus the lock and digest they must satisfy.

    Args:
        manifest_path: Manifest to read.

    Returns:
        The rendered bytes, the lock, and the lock digest.
    """
    manifest = load_manifest(manifest_path)
    snapshots = read_sources(manifest.modules)
    lock = build_lock(manifest, snapshots)
    digest = lock_digest(lock)
    rendered = rendering.render_bundle(
        bundle_id=manifest.bundle_id,
        manifest_sha256=manifest.sha256,
        lock_sha256=digest,
        snapshots=snapshots,
    )
    return rendered.data, lock, digest


def test_self_validation_rejects_a_changed_header(bundle: Bundle) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    damaged = data.replace(BUNDLE_TITLE.encode("ascii"), b"# Something Else", 1)
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(damaged, lock, digest)
    assert raised.value.problem is RenderProblem.HEADER_MISMATCH


def test_self_validation_rejects_a_wrong_lock_digest(bundle: Bundle) -> None:
    data, lock, _ = validated_parts(bundle.manifest)
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(data, lock, "c" * 64)
    assert raised.value.problem is RenderProblem.HEADER_MISMATCH


def test_self_validation_rejects_a_missing_separator(bundle: Bundle) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    damaged = data.replace(
        b"-->\n\n<!-- agents-md-compiler:module-begin",
        b"-->\n<!-- agents-md-compiler:module-begin",
        1,
    )
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(damaged, lock, digest)
    assert raised.value.problem is RenderProblem.MISSING_SEPARATOR


def test_self_validation_rejects_a_tampered_content_byte(bundle: Bundle) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    damaged = data.replace(b"Prefer the smallest", b"Prefer the largest ", 1)
    assert len(damaged) == len(data)
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(damaged, lock, digest)
    assert raised.value.problem is RenderProblem.CONTENT_DIGEST_MISMATCH


def test_self_validation_rejects_trailing_content(bundle: Bundle) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(data + b"appended\n", lock, digest)
    assert raised.value.problem is RenderProblem.TRAILING_CONTENT


def test_self_validation_rejects_truncated_bytes(bundle: Bundle) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    # Cut inside the last module's content region, so fewer bytes remain than the
    # lock declares. Cutting further back would remove the end marker instead and
    # correctly report the more specific marker mismatch.
    begin = (rendering.begin_marker(lock.modules[-1]) + "\n").encode("ascii")
    cut = data.index(begin) + len(begin) + 5
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(data[:cut], lock, digest)
    assert raised.value.problem is RenderProblem.TRUNCATED


def test_self_validation_rejects_a_marker_that_disagrees_with_the_lock(
    bundle: Bundle,
) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    assert isinstance(lock.modules[0], LockedModule)
    # The header is rebuilt from bundle_id, manifest digest, and lock digest, none
    # of which changed, so validation reaches the module marker and reports the more
    # specific mismatch there.
    relabeled = replace(
        lock, modules=(replace(lock.modules[0], id="other"), *lock.modules[1:])
    )
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(data, relabeled, digest)
    assert raised.value.problem is RenderProblem.MARKER_MISMATCH
    assert "begin other" in str(raised.value)


def test_self_validation_rejects_a_missing_end_marker(bundle: Bundle) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    damaged = data.replace(
        (rendering.end_marker(lock.modules[0]) + "\n").encode("ascii"),
        b"<!-- wrong-end -->                        \n",
        1,
    )
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(damaged, lock, digest)
    assert raised.value.problem is RenderProblem.MARKER_MISMATCH


def test_self_validation_rejects_a_begin_marker_with_a_wrong_digest(
    bundle: Bundle,
) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    damaged = data.replace(lock.modules[0].sha256.encode("ascii"), b"0" * 64, 1)
    assert len(damaged) == len(data)
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(damaged, lock, digest)
    assert raised.value.problem is RenderProblem.MARKER_MISMATCH
    assert "begin core" in str(raised.value)


def test_self_validation_rejects_a_begin_marker_with_a_wrong_byte_count(
    bundle: Bundle,
) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    declared = f"bytes={lock.modules[0].size_bytes} ".encode("ascii")
    damaged = data.replace(declared, b"bytes=9" + b" " * (len(declared) - 7), 1)
    assert len(damaged) == len(data)
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(damaged, lock, digest)
    assert raised.value.problem is RenderProblem.MARKER_MISMATCH


def test_self_validation_rejects_an_extra_module_block(bundle: Bundle) -> None:
    data, lock, digest = validated_parts(bundle.manifest)
    extra = b"\n" + (rendering.begin_marker(lock.modules[0]) + "\n").encode("ascii")
    with pytest.raises(RenderError) as raised:
        rendering.validate_rendered(data + extra, lock, digest)
    assert raised.value.problem is RenderProblem.MODULE_COUNT_MISMATCH


def test_declared_format_reads_a_generated_header(bundle: Bundle) -> None:
    data = rendered_for(bundle.manifest).data
    assert rendering.declared_format(data) == RENDER_FORMAT_VERSION


def test_declared_format_reads_a_header_when_utf8_crosses_the_probe_boundary(
    non_ascii_bundle: Bundle,
) -> None:
    data = rendered_for(non_ascii_bundle.manifest).data
    assert data[511:513] == "\u00e9".encode()
    assert rendering.declared_format(data) == RENDER_FORMAT_VERSION


def test_declared_format_reads_a_future_version() -> None:
    data = b"# Agent Instructions\n\n<!-- agents-md-compiler:generated format=7 -->\n"
    assert rendering.declared_format(data) == 7


def test_declared_format_reads_a_legacy_header() -> None:
    data = (
        b"# Global Agent Instructions\n\n"
        b"<!-- agents-md-compiler:generated format=1 -->\n"
    )
    assert rendering.declared_format(data) == 1


@pytest.mark.parametrize(
    "payload",
    [
        pytest.param(
            b"# Agent Instructions\n\n<!-- agents-md-compiler:generated format=1 -->\n",
            id="legacy-format-with-neutral-title",
        ),
        pytest.param(
            b"# Global Agent Instructions\n\n"
            b"<!-- agents-md-compiler:generated format=2 -->\n",
            id="current-format-with-legacy-title",
        ),
    ],
)
def test_declared_format_rejects_a_title_version_mismatch(payload: bytes) -> None:
    assert rendering.declared_format(payload) is None


@pytest.mark.parametrize(
    "payload",
    [
        pytest.param(b"# Hand written\n\nBody.\n", id="unmanaged-markdown"),
        pytest.param(b"", id="empty"),
        pytest.param(b"# Global Agent Instructions\n", id="title-only"),
        pytest.param(
            b"# Global Agent Instructions\nno blank line\n<!-- agents-md-compiler:generated format=1 -->\n",
            id="missing-blank-line",
        ),
        pytest.param(
            b"# Global Agent Instructions\n\n<!-- agents-md-compiler:generated -->\n",
            id="no-format-value",
        ),
        pytest.param(
            b"# Global Agent Instructions\n\n<!-- agents-md-compiler:generated format=x -->\n",
            id="non-numeric-format",
        ),
        pytest.param(
            b"# Gl\xc3\xa9bal Agent Instructions\n\n"
            b"<!-- agents-md-compiler:generated format=1 -->\n",
            id="non-ascii-title",
        ),
        pytest.param(b"\xff\xfe\x00\x01", id="not-utf8"),
    ],
)
def test_declared_format_returns_none_for_unmanaged_bytes(payload: bytes) -> None:
    assert rendering.declared_format(payload) is None


def test_compiled_bundle_self_validates(bundle: Bundle) -> None:
    compiled = compiled_for(bundle.manifest)
    assert isinstance(compiled.rendered, RenderedBundle)
    assert compiled.rendered.sha256 == sha256_bytes(compiled.rendered.data)
    assert compiled.rendered.size_bytes == len(compiled.rendered.data)
    assert compiled.lock_sha256 == sha256_bytes(compiled.lock_bytes)
