"""Immutable domain model and format constants.

Every type here is a frozen, slotted dataclass or a ``StrEnum``. Nothing in this
module performs I/O, and nothing here depends on another module in this package,
so the format constants and state tokens can be imported from anywhere without a
cycle.
"""

import re
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

MANIFEST_SCHEMA_VERSION = 1
"""Only manifest schema version this release accepts."""

LOCK_FORMAT_VERSION = 1
"""Only lock format version this release accepts."""

RENDER_FORMAT_VERSION = 1
"""Only rendered bundle format version this release produces or adopts."""

RECEIPT_SCHEMA_VERSION = 1
"""Only receipt schema version this release writes."""

JSON_SCHEMA_VERSION = 1
"""Version of the CLI JSON envelope."""

IDENTIFIER_PATTERN = re.compile(r"\A[a-z][a-z0-9-]{0,63}\Z")
"""Bundle and module identifier pattern, narrow enough for use inside markers."""

SHA256_PATTERN = re.compile(r"\A[0-9a-f]{64}\Z")
"""Lowercase hexadecimal SHA-256 digest."""

MARKER_PREFIX = b"<!-- agents-md-compiler:"
"""Compiler-owned marker prefix. A source containing it anywhere is rejected."""

BUNDLE_TITLE = "# Global Agent Instructions"
"""First line of every rendered bundle."""

DO_NOT_EDIT_NOTICE = (
    "<!-- Do not edit this file. Edit canonical sources and regenerate it. -->"
)
"""Last header line of every rendered bundle."""

LOCK_SUFFIX = ".lock.json"
"""Appended to a manifest path to form the default lock path."""

OVERRIDE_FILENAME = "AGENTS.override.md"
"""Global file Codex prefers over ``AGENTS.md`` when it is non-empty."""

GLOBAL_TARGET_FILENAME = "AGENTS.md"
"""Target name that makes override shadowing applicable."""

DISTRIBUTION_DIRECTORY = "agents-md-compiler"
"""Directory name used under the platform user state root."""

NEW_TARGET_MODE = 0o600
"""Mode applied to a target this tool creates. An existing mode is preserved."""

STATE_DIR_MODE = 0o700
"""Mode applied to state directories this tool creates."""

STATE_FILE_MODE = 0o600
"""Mode applied to backups and receipts this tool creates."""


class BundleState(StrEnum):
    """Externally visible state tokens.

    These appear in JSON envelopes, receipts, and exit-code mapping, so the string
    values are a public contract.
    """

    CURRENT = "CURRENT"
    DRIFTED = "DRIFTED"
    MISSING = "MISSING"
    SHADOWED = "SHADOWED"
    INVALID_MANIFEST = "INVALID_MANIFEST"
    INVALID_LOCK = "INVALID_LOCK"
    LOCK_MISSING = "LOCK_MISSING"
    LOCK_STALE = "LOCK_STALE"
    INVALID_SOURCE = "INVALID_SOURCE"
    UNMANAGED_TARGET = "UNMANAGED_TARGET"
    CONCURRENT_CHANGE = "CONCURRENT_CHANGE"
    RUNTIME_UNVERIFIED = "RUNTIME_UNVERIFIED"


class TargetKind(StrEnum):
    """How an existing target relates to this compiler."""

    MISSING = "MISSING"
    MANAGED = "MANAGED"
    UNMANAGED = "UNMANAGED"


@dataclass(frozen=True, slots=True)
class PathPair:
    """A path as the operator wrote it and as the filesystem call used it.

    Attributes:
        lexical: The operator-supplied form, unmodified.
        resolved: The absolute normalized form actually used.
    """

    lexical: str
    resolved: str


@dataclass(frozen=True, slots=True)
class BundleLimits:
    """Bounds that keep a hostile or accidental input from exhausting memory.

    Defaults are generous. A violation names the limit and the observed size rather
    than truncating.

    Attributes:
        max_source_bytes: Largest accepted single canonical source.
        max_bundle_bytes: Largest accepted total of all source bytes.
        max_modules: Largest accepted module count.
        max_manifest_bytes: Largest accepted manifest file.
    """

    max_source_bytes: int = 4 * 1024 * 1024
    max_bundle_bytes: int = 32 * 1024 * 1024
    max_modules: int = 256
    max_manifest_bytes: int = 1024 * 1024


@dataclass(frozen=True, slots=True)
class ModuleSpec:
    """One module as selected by the manifest, before its bytes are read.

    Attributes:
        id: Module identifier, validated against :data:`IDENTIFIER_PATTERN`.
        lexical_source: The source path exactly as the manifest wrote it.
        source: Absolute normalized source path, resolved without following links.
    """

    id: str
    lexical_source: str
    source: Path


@dataclass(frozen=True, slots=True)
class BundleManifest:
    """A parsed, path-resolved manifest.

    Attributes:
        schema_version: Always :data:`MANIFEST_SCHEMA_VERSION`.
        bundle_id: Bundle identifier.
        default_target: Absolute normalized default install target.
        lexical_default_target: The target path as the manifest wrote it.
        modules: Modules in manifest order, which is output order.
        path: Absolute normalized manifest path.
        lexical_path: The manifest path as the operator supplied it.
        sha256: Digest of the exact manifest file bytes.
        size_bytes: Manifest file size.
    """

    schema_version: int
    bundle_id: str
    default_target: Path
    lexical_default_target: str
    modules: tuple[ModuleSpec, ...]
    path: Path
    lexical_path: str
    sha256: str
    size_bytes: int


@dataclass(frozen=True, slots=True)
class SourceSnapshot:
    """Validated bytes of one canonical source, read exactly once.

    Hashing and rendering both use this snapshot rather than reading the file
    again, so a source cannot change between those operations unnoticed.

    Attributes:
        id: Module identifier.
        lexical_source: The source path as the manifest wrote it.
        resolved_source: Absolute normalized source path.
        data: Exact accepted source bytes.
        sha256: Digest of ``data``.
        size_bytes: Length of ``data``.
    """

    id: str
    lexical_source: str
    resolved_source: Path
    data: bytes
    sha256: str
    size_bytes: int


@dataclass(frozen=True, slots=True)
class LockedModule:
    """One module's recorded identity.

    Attributes:
        id: Module identifier.
        resolved_source: Absolute source path recorded at lock time.
        sha256: Digest of the canonical source bytes.
        size_bytes: Canonical source byte count.
    """

    id: str
    resolved_source: str
    sha256: str
    size_bytes: int


@dataclass(frozen=True, slots=True)
class BundleLock:
    """A parsed lock document.

    Attributes:
        bundle_id: Bundle identifier copied from the manifest.
        format_version: Always :data:`LOCK_FORMAT_VERSION`.
        manifest_sha256: Digest of the exact manifest bytes at lock time.
        modules: Locked modules in manifest order.
    """

    bundle_id: str
    format_version: int
    manifest_sha256: str
    modules: tuple[LockedModule, ...]


@dataclass(frozen=True, slots=True)
class RenderedBundle:
    """Rendered bytes plus the identity they encode.

    Attributes:
        data: Exact rendered bytes.
        sha256: Digest of ``data``.
        size_bytes: Length of ``data``.
        bundle_id: Bundle identifier written into the header.
        manifest_sha256: Manifest digest written into the header.
        lock_sha256: Canonical lock digest written into the header.
        modules: Locked modules in output order.
    """

    data: bytes
    sha256: str
    size_bytes: int
    bundle_id: str
    manifest_sha256: str
    lock_sha256: str
    modules: tuple[LockedModule, ...]


@dataclass(frozen=True, slots=True)
class CompiledBundle:
    """Everything a read-only command needs, computed without mutating anything.

    Attributes:
        manifest: The parsed manifest.
        lock: The lock freshly built from the validated snapshots.
        lock_bytes: Canonical serialization of ``lock``.
        lock_sha256: Digest of ``lock_bytes``.
        rendered: The rendered bundle.
    """

    manifest: BundleManifest
    lock: BundleLock
    lock_bytes: bytes
    lock_sha256: str
    rendered: RenderedBundle


@dataclass(frozen=True, slots=True)
class TargetInspection:
    """What the filesystem says about a target, without following a link.

    Attributes:
        path: Absolute normalized target path.
        lexical_path: The target path as supplied.
        kind: Whether the target is missing, managed, or unmanaged.
        sha256: Digest of the existing bytes, or ``None`` when absent.
        size_bytes: Size of the existing file, or ``None`` when absent.
        mode: Permission bits of the existing file, or ``None`` when absent.
        is_symlink: Whether the path itself is a symbolic link.
        declared_format: Format value from a recognized generated header.
    """

    path: Path
    lexical_path: str
    kind: TargetKind
    sha256: str | None
    size_bytes: int | None
    mode: int | None
    is_symlink: bool
    declared_format: int | None


@dataclass(frozen=True, slots=True)
class OverrideInspection:
    """Whether a shadowing global override exists beside the target.

    Attributes:
        path: The override path that would apply, or ``None`` when the target name
            makes shadowing inapplicable.
        present: Whether that override exists and is non-empty.
    """

    path: Path | None
    present: bool


@dataclass(frozen=True, slots=True)
class BundleStatus:
    """The result of a read-only evaluation.

    Attributes:
        state: First applicable state in documented precedence order.
        compiled: The compiled bundle. Always present, because evaluation raises on
            an invalid manifest, source, or lock rather than returning a status
            without one.
        target: Target inspection, or ``None`` when no target applies.
        override: Override inspection.
        lock_present: Whether a lock file exists at the resolved lock path.
        lock_matches: Whether the on-disk lock equals a freshly serialized lock.
    """

    state: BundleState
    compiled: CompiledBundle
    target: TargetInspection | None
    override: OverrideInspection
    lock_present: bool
    lock_matches: bool


@dataclass(frozen=True, slots=True)
class ModuleDigest:
    """One module's identity as recorded in a receipt.

    A receipt records identity without the resolved source path, because a receipt
    is an operational record of what was installed rather than a source pin.

    Attributes:
        id: Module identifier.
        sha256: Digest of the canonical source bytes.
        size_bytes: Canonical source byte count.
    """

    id: str
    sha256: str
    size_bytes: int


@dataclass(frozen=True, slots=True)
class BackupRecord:
    """An immutable copy of a target's prior bytes.

    Attributes:
        path: Backup file path under the bundle state root.
        sha256: Digest of the backed-up bytes.
        size_bytes: Size of the backed-up bytes.
    """

    path: Path
    sha256: str
    size_bytes: int


@dataclass(frozen=True, slots=True)
class PreviousTargetRecord:
    """The target's state immediately before a mutation, captured under the lock.

    Attributes:
        state: Whether the target was missing, managed, or unmanaged.
        sha256: Digest of the prior bytes, or ``None`` when absent.
        size_bytes: Size of the prior bytes, or ``None`` when absent.
        mode: Prior permission bits, or ``None`` when absent.
    """

    state: TargetKind
    sha256: str | None
    size_bytes: int | None
    mode: int | None


@dataclass(frozen=True, slots=True)
class WrittenRecord:
    """Bytes this tool wrote to a target.

    Attributes:
        sha256: Digest of the written bytes.
        size_bytes: Number of bytes written.
        mode: Permission bits applied.
    """

    sha256: str
    size_bytes: int
    mode: int


@dataclass(frozen=True, slots=True)
class SourceReceiptRef:
    """The install receipt a rollback consumed.

    Attributes:
        path: Receipt path.
        sha256: Digest of the receipt bytes.
        operation_id: Operation identifier recorded in that receipt.
    """

    path: Path
    sha256: str
    operation_id: str


@dataclass(frozen=True, slots=True)
class InstallReceipt:
    """A validated install receipt.

    Attributes:
        path: Where this receipt itself lives.
        sha256: Digest of the receipt bytes as read.
        schema_version: Always :data:`RECEIPT_SCHEMA_VERSION`.
        operation_id: Identifier for the install this receipt records.
        compiler_version: Distribution version that performed the install.
        bundle_id: Bundle identifier.
        manifest: Manifest path pair at install time.
        lock: Lock path pair at install time.
        target: Target path pair at install time.
        manifest_sha256: Manifest digest at install time.
        lock_sha256: Canonical lock digest at install time.
        modules: Module identity at install time, in manifest order.
        previous_target: Target state before the install.
        backup: Backup of the prior bytes, or ``None`` when none existed.
        installed: Bytes the install wrote.
        completed_at: UTC completion time, second precision.
    """

    path: Path
    sha256: str
    schema_version: int
    operation_id: str
    compiler_version: str
    bundle_id: str
    manifest: PathPair
    lock: PathPair
    target: PathPair
    manifest_sha256: str
    lock_sha256: str
    modules: tuple[ModuleDigest, ...]
    previous_target: PreviousTargetRecord
    backup: BackupRecord | None
    installed: WrittenRecord
    completed_at: str


@dataclass(frozen=True, slots=True)
class InstallPlan:
    """What an install would do, computed without mutating anything.

    Attributes:
        target: Resolved target path pair.
        previous_target: Target state as captured before the mutation.
        output_sha256: Digest of the bytes that would be written.
        output_bytes: Number of bytes that would be written.
        target_mode: Permission bits that would be applied.
        backup_path: Backup path that would be written, or ``None``.
        adoption_required: Whether replacing this target needs explicit adoption.
        state_dir: Per-bundle state directory.
        already_current: Whether the target already equals the rendered bytes.
    """

    target: PathPair
    previous_target: PreviousTargetRecord
    output_sha256: str
    output_bytes: int
    target_mode: int
    backup_path: Path | None
    adoption_required: bool
    state_dir: Path
    already_current: bool


@dataclass(frozen=True, slots=True)
class InstallOutcome:
    """The result of an install, applied or previewed.

    Attributes:
        state: Reported state, ``CURRENT`` after a successful apply.
        applied: Whether the mutation was performed.
        plan: The plan that was computed.
        backup: Backup written, or ``None``.
        installed: Bytes written, or ``None`` for a dry run.
        receipt_path: Receipt written, or ``None`` for a dry run.
        operation_id: Identifier for this operation.
        completed_at: UTC completion time, or ``None`` for a dry run.
    """

    state: BundleState
    applied: bool
    plan: InstallPlan
    backup: BackupRecord | None
    installed: WrittenRecord | None
    receipt_path: Path | None
    operation_id: str
    completed_at: str | None


@dataclass(frozen=True, slots=True)
class RollbackOutcome:
    """The result of a rollback, applied or previewed.

    Attributes:
        state: Reported state after the rollback.
        applied: Whether the mutation was performed.
        receipt: The install receipt that was consumed.
        restored: Bytes restored, or ``None`` when the target was preserved instead.
        preserved_path: Where a generated target was moved when no backup existed.
        receipt_path: Rollback receipt written, or ``None`` for a dry run.
        operation_id: Identifier for this operation.
        completed_at: UTC completion time, or ``None`` for a dry run.
    """

    state: BundleState
    applied: bool
    receipt: InstallReceipt
    restored: WrittenRecord | None
    preserved_path: Path | None
    receipt_path: Path | None
    operation_id: str
    completed_at: str | None
